name: Deploy organization lambda dev

on:
  push:
    branches:
      - development

env:
  REGION: ${{ secrets.REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-organization:
    name: Build code
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ env.REGION }}

      - name: Run deploy code dev-create-personal-plan-fingo
        run: |
          cd src/fingo-create-personal-plan-service/src
          pip install -r requirements.txt --target .
          find . -name '*.pyc' -delete
          zip -r build.zip .
          ls
          aws lambda update-function-code  \
            --function-name dev-create-personal-plan-fingo \
            --zip-file fileb://build.zip

      - name: Run deploy code dev-handle-personal-plan-status-fingo
        run: |
          cd src/fingo-handle-personal-plan-status-service/src
          pip install -r requirements.txt --target .
          find . -name '*.pyc' -delete
          zip -r build.zip .
          ls
          aws lambda update-function-code  \
            --function-name dev-handle-personal-plan-status-fingo \
            --zip-file fileb://build.zip


      - name: Run deploy code dev-consult-personal-plans-fingo
        run: |
          cd src/fingo-consult-personal-plans-service/src
          pip install -r requirements.txt --target .
          find . -name '*.pyc' -delete
          zip -r build.zip .
          ls
          aws lambda update-function-code  \
            --function-name dev-consult-personal-plans-fingo \
            --zip-file fileb://build.zip